### ISSUE TITLE
Ocean NPP notebook is broken

### ISSUE THREAD

**Issue by wildintellect** [NASA-IMPACT/veda-docs#132]
@freitagb reported there's an issue in https://nasa-impact.github.io/veda-docs/notebooks/datasets/ocean-npp-timeseries-analysis.html#the-case-study---walvis-bay-namibia

```
# the bounding box should be passed to the geojson param as a geojson Feature or FeatureCollection
def generate_stats(item, geojson):
    result = requests.post(
        f"{RASTER_API_URL}/cog/statistics",
        params={"url": item["assets"]["cog_default"]["href"]},
        json=geojson,
    ).json()
    return {
        **result["properties"],
        "start_datetime": item["properties"]["start_datetime"],
    }
the return statement here no longer works because the response structure from the API has changed (at least i think that's why). For example it works if i do
    return {
        **result["features"][0]["properties"],
        "start_datetime": item["properties"]["datetime"],
    }
```

**Comment by jsignell** [comment]
I can't reproduce the notebook works fine for me on vedahub with the latest pangeo image. I looked at the docs though and it does seem like the response can potentially be either a feature or a feature collection https://staging-raster.delta-backend.com/docs#/Cloud%20Optimized%20GeoTIFF/geojson_statistics_cog_statistics_post 

I guess we could genearalize that function to expect either, but it seems like the API should guarantee the shape of the response.

**Comment by wildintellect** [comment]
let's pass this over to the Data Service team to review then. cc @smohiudd @anayeaye

**Comment by anayeaye** [comment]
So is the issue here that (I've just read this issue and the notebook and haven't tried to test this yet):

Feature in = Feature out
If you request cog/statistics with a feature collection you get a response that is a feature collection of the stats in each feature's properties. 

Feature Collection in = Feature Collection out
And if you request cog/statistics with a single feature then you get a response that is a single feature including stats in that feature's properties. 

So we need to 
- [ ] update the API docs to show schema in = schema out (Feature Collection-> Feature Collection, Feature -> Feature)? 
- [ ] maybe update the language some in that notebook, too, for clarity

OR are we saying that one API should always return the same format, i.e. you request with a single Feature or Feature Collection, we always return a Feature Collection?

**Comment by jsignell** [comment]
That's a nice summary. This was my intent:

> are we saying that one API should always return the same format, i.e. you request with a single Feature or Feature Collection, we always return a Feature Collection?

But that is really a question for titiler. Normally I expect APIs to return a consistent type. But I guess as long as the input matches the output that is a reasonable pattern too. I guess I'd want to make sure that if I pass a feature collection with just one feature I still get a feature collection out. If that is the case then I can be happy.

**Comment by wildintellect** [comment]
@zacharyDez @vincentsarago have opinions on this?

**Comment by jsignell** [comment]
Ok. So we can't reproduce the original issue and it seems like titiler is working as expected. So it's just a documentation problem.

**Comment by wildintellect** [comment]
https://github.com/NASA-IMPACT/veda-docs/pull/133
